= Computer Vision and Pattern Recognition
:toc:
:toc-title: Contents
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :warning:
:format-caption:
endif::[]
:repoURL: https://github.com/amrut-prabhu/computer-vision/blob/master

== About this repository

This repository is a collection of basic computer vision and image processing techniques. The implementations of the algorithms are in MATLAB.

== Histogram Equilization

Image processing technique.
See more details {repoURL}/histogram_equilization/histogram_equilization.adoc[here].

*Code*

* {repoURL}/histogram_equilization/histogram_eq.m[Implementation of algorithm]
* {repoURL}/histogram_equilization/histogram_eq_function.m[Using built-in functions]

== Contrast Stretching

Image processing technique.
See more details {repoURL}/contrast_stretch/contrast_stretch.adoc[here].

*Code*

* {repoURL}/contrast_stretch/contrast_stretch.m[Implementation of algorithm]
* {repoURL}/contrast_stretch/contrast_stretch_function.m[Using built-in functions]

== Edge Detection

Image processing technique.
See more details {repoURL}/edge_detection/edge_detection.adoc[here].

*Code*

* {repoURL}/edge_detection/edge_detection.m[Implementation of Sobel edge detector]
* {repoURL}/edge_detection/edge_detection_function.m[Using built-in functions]

== Background Removal

Image processing technique.
See more details {repoURL}/background_removal/background_removal.adoc[here].

*Code*

* {repoURL}/background_removal/background.m[Implementation of Background Removal]
* {repoURL}/background_removal/background_function.m[Using built-in functions]

== Background Foreground Separation

Foreground detection and Background subtraction is a major tasks in Computer Vision and Image processing.
See more details {repoURL}/background_foreground_separation/background_foreground_separation.adoc[here].

*Code*

* {repoURL}/background_foreground_separation/counting_vehicles.m[Implementation of Counting Vehicles algorithm]
